// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKUXk2lorDnyzOklzd18f3A9IXJIdO2DI',
    appId: '1:678090654322:web:42399c9708c6f18d78b8eb',
    messagingSenderId: '678090654322',
    projectId: 'studimi-project',
    authDomain: 'studimi-project.firebaseapp.com',
    storageBucket: 'studimi-project.appspot.com',
    measurementId: 'G-KQ2F5C4BBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMLP0ELsj7fRHP9KqSoGulTbaEokXslA',
    appId: '1:678090654322:android:ab19ae96341a700578b8eb',
    messagingSenderId: '678090654322',
    projectId: 'studimi-project',
    storageBucket: 'studimi-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmO3eGxltldGqz2hALHdPD6DhMTc6iE6w',
    appId: '1:678090654322:ios:9d00a331d0ef382b78b8eb',
    messagingSenderId: '678090654322',
    projectId: 'studimi-project',
    storageBucket: 'studimi-project.appspot.com',
    iosClientId: '678090654322-qrmpkn2q5mhs21d0sr1mcgc6r4o5266d.apps.googleusercontent.com',
    iosBundleId: 'com.example.studimi',
  );
}
